force-app/main/default/objects/Beneficiario__c/Beneficiario__c.object-meta.xml
<CustomObject>
    <label>Beneficiario</label>
    <nameField>
        <label>Nombre de Beneficiario</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beneficiarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Beneficiario__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Beneficiarios</relationshipLabel>
    <relationshipName>Beneficiarios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Beneficiario__c.field-meta.xml
<CustomField>
    <fullName>Beneficiario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beneficiario</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratos (Beneficiario)</relationshipLabel>
    <relationshipName>Contratos_Beneficiario</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Contratista__c.field-meta.xml
<CustomField>
    <fullName>Contratista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratista</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratos (Contratista)</relationshipLabel>
    <relationshipName>Contratos_Contratista</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Institucion__c.field-meta.xml
<CustomField>
    <fullName>Institucion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Institución (Afianzadora)</label>
    <referenceTo>Institucion__c</referenceTo>
    <relationshipLabel>Contratos (Afianzadora)</relationshipLabel>
    <relationshipName>Contratos_Std_Institucion</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Precalificacion__c.field-meta.xml
<CustomField>
    <fullName>Precalificacion__c</fullName>
    <label>Precalificación</label>
    <referenceTo>Precalificacion__c</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Vendedores__c</referenceTo>
    <relationshipLabel>Contractos</relationshipLabel>
    <relationshipName>Contractos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contratista__c/Contratista__c.object-meta.xml
<CustomObject>
    <label>Contratista</label>
    <nameField>
        <label>Nombre de Contratista</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratistas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contratista__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contratistas</relationshipLabel>
    <relationshipName>Contratistas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <label>Contrato</label>
    <nameField>
        <label>No. Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato__c/fields/Beneficiario__c.field-meta.xml
<CustomField>
    <fullName>Beneficiario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beneficiario</label>
    <referenceTo>Beneficiario__c</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Contratista__c.field-meta.xml
<CustomField>
    <fullName>Contratista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratista</label>
    <referenceTo>Contratista__c</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos_Contratista</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <formula>IF(
    TODAY() &lt;=  Fin_de_Contrato__c ,
    &quot;En plazo&quot;,
    &quot;Vencido&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estatus</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Institucion__c.field-meta.xml
<CustomField>
    <fullName>Institucion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Institución</label>
    <referenceTo>Institucion__c</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos_Institucion</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Institucion__c/Institucion__c.object-meta.xml
<CustomObject>
    <label>Institución</label>
    <nameField>
        <label>Nombre de la Institución</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instituciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Institucion__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activa</fullName>
            </value>
            <value>
                <fullName>Desactiva</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Beneficiario__c.field-meta.xml
<CustomField>
    <fullName>Beneficiario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beneficiario</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oportunidades (Beneficiario)</relationshipLabel>
    <relationshipName>Oportunidades_Beneficiario</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contratista__c.field-meta.xml
<CustomField>
    <fullName>Contratista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratista</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oportunidades (Contratista)</relationshipLabel>
    <relationshipName>Oportunidades_Contratista</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Institucion__c.field-meta.xml
<CustomField>
    <fullName>Institucion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Institución</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Institución</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oportunidades (Institución)</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Periodo_Pago__c.field-meta.xml
<CustomField>
    <fullName>Periodo_Pago__c</fullName>
    <label>Periodo Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Periodo_Pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Precalificacion__c.field-meta.xml
<CustomField>
    <fullName>Precalificacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup a la Precalificación que originó esta oportunidad. El Score ICP y el motivo viven en Precalificacion__c (no en Opportunity) para mantener separación semántica.</description>
    <label>Precalificación</label>
    <referenceTo>Precalificacion__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Precalificacion__c/Precalificacion__c.object-meta.xml
<CustomObject>
    <label>Precalificación</label>
    <nameField>
        <label>Nombre de Precalificación</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Precalificaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Precalificacion__c/fields/Contratista__c.field-meta.xml
<CustomField>
    <fullName>Contratista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratista</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Precalificaciones</relationshipLabel>
    <relationshipName>Precalificaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Fianza__c/Tech_Fianza__c.object-meta.xml
<CustomObject>
    <label>Fianza</label>
    <nameField>
        <displayFormat>Fi-{0000}</displayFormat>
        <label>Número de fianza</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fianzas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tech_Fianza__c/fields/Afianzadoras__c.field-meta.xml
<CustomField>
    <fullName>Afianzadoras__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Afianzadora</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fianzas</relationshipLabel>
    <relationshipName>Fianzas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Fianza__c/fields/Beneficiarios__c.field-meta.xml
<CustomField>
    <fullName>Beneficiarios__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beneficiario</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fianzas (Beneficiario)</relationshipLabel>
    <relationshipName>Fianzas2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Fianza__c/fields/Contratistas__c.field-meta.xml
<CustomField>
    <fullName>Contratistas__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratista</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fianzas (Contratista)</relationshipLabel>
    <relationshipName>Fianzas3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Fianza__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Fianzas</relationshipLabel>
    <relationshipName>Fianzas_Tech</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Fianza__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Emitida</fullName>
            </value>
            <value>
                <fullName>Vigente</fullName>
            </value>
            <value>
                <fullName>Vencida</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Reclamada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tech_Fianza__c/fields/Fecha_de_Emision__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Emision__c</fullName>
    <label>Fecha de emisión</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tech_Fianza__c/fields/Fecha_de_Vencimiento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Vencimiento__c</fullName>
    <label>Fecha de vencimiento (original)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tech_Fianza__c/fields/Fecha_Vencimiento_Vigente__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Vencimiento_Vigente__c</fullName>
    <label>Fecha vencimiento vigente</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tech_Fianza__c/fields/Institucion__c.field-meta.xml
<CustomField>
    <fullName>Institucion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Institución</label>
    <referenceTo>Institucion__c</referenceTo>
    <relationshipLabel>Fianzas</relationshipLabel>
    <relationshipName>Fianzas_Institucion</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Fianza__c/fields/Monto_Afianzado__c.field-meta.xml
<CustomField>
    <fullName>Monto_Afianzado__c</fullName>
    <label>Monto afianzado (original)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tech_Fianza__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Fianzas</relationshipLabel>
    <relationshipName>Fianzas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Fianza__c/fields/Periodo_Pago__c.field-meta.xml
<CustomField>
    <fullName>Periodo_Pago__c</fullName>
    <label>Periodo Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Periodo_Pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tech_Fianza__c/fields/Prima_neta__c.field-meta.xml
<CustomField>
    <fullName>Prima_neta__c</fullName>
    <label>Prima neta (original)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tech_Fianza__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Tech_Vendedor__c</referenceTo>
    <relationshipLabel>Fianzas</relationshipLabel>
    <relationshipName>Fianzas_Vendedor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TechFianzaTriggerHandler.cls
public without sharing class TechFianzaTriggerHandler {

    /*
     * =====================================================================================
     * CLASE: TechFianzaTriggerHandler
     * =====================================================================================
     *
     * Objetivo:
     * - Validar que toda fianza nazca desde Contract.
     * - Bloquear nuevas fianzas desde Opportunity.
     * - Validar precalificación suficiente.
     * - Heredar datos del contrato.
     * - Generar plan y recibos para fianzas manuales.
     *
     * Regla:
     * - El flujo nuevo de fianzas es:
     *      Contract → Precalificación → Tech_Fianza__c → Plan de Pago → Recibos.
     */

    private static Boolean enEjecucionAfter = false;

    private static final String CAPACIDAD_SUFICIENTE = 'Capacidad Suficiente';
    private static final String ESTATUS_FIANZA_EMITIDA = 'Emitida';

    /*
     * =====================================================================================
     * BEFORE INSERT / BEFORE UPDATE
     * =====================================================================================
     */
    public static void beforeSave(
        List<Tech_Fianza__c> nuevasFianzas,
        Map<Id, Tech_Fianza__c> fianzasAnteriores
    ) {

        if (nuevasFianzas == null || nuevasFianzas.isEmpty()) {
            return;
        }

        Set<Id> contractIds = new Set<Id>();

        /*
         * -------------------------------------------------------------------------
         * 1. Validaciones iniciales
         * -------------------------------------------------------------------------
         */
        for (Tech_Fianza__c fianza : nuevasFianzas) {

            if (fianza == null) {
                continue;
            }

            Id contratoId = getId(fianza, 'Contrato__c');

            if (contratoId == null) {
                fianza.addError(
                    'La fianza debe estar relacionada con un contrato.'
                );
                continue;
            }

            /*
             * Las nuevas fianzas ya no deben nacer desde Opportunity.
             * Se permite que el campo exista solo como histórico.
             */
            if (fianza.Oportunidad__c != null) {
                fianza.addError(
                    'El nuevo proceso de fianzas no permite crear fianzas desde Opportunity. ' +
                    'La fianza debe nacer desde Contract.'
                );
                continue;
            }

            /*
             * No permitir cambiar el contrato de una fianza existente.
             */
            if (
                fianzasAnteriores != null &&
                fianza.Id != null &&
                fianzasAnteriores.containsKey(fianza.Id)
            ) {
                Tech_Fianza__c anterior = fianzasAnteriores.get(fianza.Id);

                Id contratoAnteriorId = getId(anterior, 'Contrato__c');

                if (
                    contratoAnteriorId != null &&
                    contratoAnteriorId != contratoId
                ) {
                    fianza.addError(
                        'No se permite cambiar el contrato de una fianza existente.'
                    );
                    continue;
                }
            }

            contractIds.add(contratoId);
        }

        if (contractIds.isEmpty()) {
            return;
        }

        /*
         * -------------------------------------------------------------------------
         * 2. Consultar contratos y validar precalificación
         * -------------------------------------------------------------------------
         */
        Map<Id, SObject> contratosPorId = obtenerContratos(contractIds);

        Set<Id> contratosConPrecalificacion =
            obtenerContratosConPrecalificacionSuficiente(contratosPorId);

        /*
         * -------------------------------------------------------------------------
         * 3. Heredar datos y validar datos financieros
         * -------------------------------------------------------------------------
         */
        for (Tech_Fianza__c fianza : nuevasFianzas) {

            if (fianza == null) {
                continue;
            }

            Id contratoId = getId(fianza, 'Contrato__c');

            if (contratoId == null) {
                continue;
            }

            if (!contratosPorId.containsKey(contratoId)) {
                fianza.addError(
                    'No fue posible localizar el contrato relacionado.'
                );
                continue;
            }

            if (!contratosConPrecalificacion.contains(contratoId)) {
                fianza.addError(
                    'No se puede emitir la fianza. El contrato debe contar con una ' +
                    'precalificación con Capacidad Afianzamiento Calc = "Capacidad Suficiente".'
                );
                continue;
            }

            heredarDatosContrato(
                fianza,
                contratosPorId.get(contratoId)
            );

            validarDatosFinancieros(fianza);
        }
    }

    /*
     * =====================================================================================
     * AFTER INSERT / AFTER UPDATE
     * =====================================================================================
     */
    public static void afterSave(
        List<Tech_Fianza__c> fianzas,
        Map<Id, Tech_Fianza__c> fianzasAnteriores
    ) {

        if (enEjecucionAfter) {
            return;
        }

        /*
         * Si la fianza fue creada desde TechFianzaContratoService,
         * el servicio genera los planes para evitar duplicidad.
         */
        if (TechFianzaContratoService.estaEjecutandoCreacionDesdeContrato()) {
            return;
        }

        if (fianzas == null || fianzas.isEmpty()) {
            return;
        }

        enEjecucionAfter = true;

        try {

            Set<Id> fianzaIdsParaPlan = new Set<Id>();

            for (Tech_Fianza__c fianza : fianzas) {

                if (fianza == null || fianza.Id == null) {
                    continue;
                }

                if (fianza.Prima_neta__c == null || fianza.Prima_neta__c <= 0) {
                    continue;
                }

                fianzaIdsParaPlan.add(fianza.Id);
            }

            if (!fianzaIdsParaPlan.isEmpty()) {
                TechPlanPagoService.generarPlanesYRecibosPorFianzaIds(
                    fianzaIdsParaPlan
                );
            }

        } finally {
            enEjecucionAfter = false;
        }
    }

    /*
     * =====================================================================================
     * HERENCIA DE DATOS DESDE CONTRACT
     * =====================================================================================
     */
    private static void heredarDatosContrato(
        Tech_Fianza__c fianza,
        SObject contrato
    ) {

        if (fianza == null || contrato == null) {
            return;
        }

        Id contratistaId = getId(contrato, 'Contratista__c');

        if (contratistaId == null) {
            contratistaId = getId(contrato, 'AccountId');
        }

        Id beneficiarioId = getId(contrato, 'Beneficiario__c');

        if (beneficiarioId == null) {
            beneficiarioId = getId(contrato, 'AccountId');
        }

        if (fianza.Contratistas__c == null) {
            fianza.Contratistas__c = contratistaId;
        }

        if (fianza.Beneficiarios__c == null) {
            fianza.Beneficiarios__c = beneficiarioId;
        }

        // Afianzadoras__c es lookup a Account; Institucion__c del contrato es objeto custom incompatible.
        // La institución se hereda vía Institucion__c (mismo tipo) — no asignar aquí.

        if (fianza.Vendedor__c == null) {
            fianza.Vendedor__c = getId(contrato, 'Vendedor__c');
        }

        if (String.isBlank(fianza.Periodo_Pago__c)) {
            fianza.Periodo_Pago__c = getString(contrato, 'Periodo_Pago__c');
        }

        if (String.isBlank(fianza.Periodo_Pago__c)) {
            fianza.Periodo_Pago__c = 'Contado';
        }

        if (fianza.Fecha_de_Emision__c == null) {

            Date fechaInicio = getDate(contrato, 'Fecha_Inicio__c');

            if (fechaInicio == null) {
                fechaInicio = getDate(contrato, 'StartDate');
            }

            fianza.Fecha_de_Emision__c = fechaInicio;
        }

        if (fianza.Fecha_de_Vencimiento__c == null) {

            Date fechaFin = getDate(contrato, 'Fecha_Fin_Vigente__c');

            if (fechaFin == null) {
                fechaFin = getDate(contrato, 'Fecha_Fin__c');
            }

            if (fechaFin == null) {
                fechaFin = getDate(contrato, 'EndDate');
            }

            fianza.Fecha_de_Vencimiento__c = fechaFin;
        }

        if (fianza.Fecha_Vencimiento_Vigente__c == null) {
            fianza.Fecha_Vencimiento_Vigente__c =
                fianza.Fecha_de_Vencimiento__c;
        }

        if (String.isBlank(fianza.Estatus__c)) {
            fianza.Estatus__c = ESTATUS_FIANZA_EMITIDA;
        }
    }

    /*
     * =====================================================================================
     * VALIDACIONES FINANCIERAS Y DE VIGENCIA
     * =====================================================================================
     */
    private static void validarDatosFinancieros(Tech_Fianza__c fianza) {

        if (fianza == null) {
            return;
        }

        if (fianza.Monto_Afianzado__c == null || fianza.Monto_Afianzado__c <= 0) {
            fianza.addError(
                'La fianza debe tener Monto Afianzado mayor a cero.'
            );
        }

        if (fianza.Prima_neta__c == null || fianza.Prima_neta__c <= 0) {
            fianza.addError(
                'La fianza debe tener Prima Neta mayor a cero.'
            );
        }

        if (fianza.Fecha_de_Emision__c == null) {
            fianza.addError(
                'La fianza debe tener Fecha de Emisión.'
            );
        }

        if (fianza.Fecha_de_Vencimiento__c == null) {
            fianza.addError(
                'La fianza debe tener Fecha de Vencimiento.'
            );
        }

        if (
            fianza.Fecha_de_Emision__c != null &&
            fianza.Fecha_de_Vencimiento__c != null &&
            fianza.Fecha_de_Vencimiento__c <= fianza.Fecha_de_Emision__c
        ) {
            fianza.addError(
                'La Fecha de Vencimiento debe ser mayor que la Fecha de Emisión.'
            );
        }
    }

    /*
     * =====================================================================================
     * CONSULTA DE CONTRACT
     * =====================================================================================
     */
    private static Map<Id, SObject> obtenerContratos(Set<Id> contractIds) {

        Map<Id, SObject> contratosPorId = new Map<Id, SObject>();

        if (contractIds == null || contractIds.isEmpty()) {
            return contratosPorId;
        }

        List<String> campos = new List<String>{
            'Id',
            'AccountId',
            'StartDate',
            'EndDate',
            'Status',
            'ContractNumber'
        };

        /*
         * Corrección principal:
         * Usamos DescribeSObjectResult y el helper ahora sí acepta este tipo.
         */
        Schema.DescribeSObjectResult contractDescribe =
            Contract.SObjectType.getDescribe();

        agregarCampoSiExiste(contractDescribe, campos, 'Contratista__c');
        agregarCampoSiExiste(contractDescribe, campos, 'Beneficiario__c');
        agregarCampoSiExiste(contractDescribe, campos, 'Institucion__c');
        agregarCampoSiExiste(contractDescribe, campos, 'Vendedor__c');
        agregarCampoSiExiste(contractDescribe, campos, 'Fecha_Inicio__c');
        agregarCampoSiExiste(contractDescribe, campos, 'Fecha_Fin__c');
        agregarCampoSiExiste(contractDescribe, campos, 'Fecha_Fin_Vigente__c');
        agregarCampoSiExiste(contractDescribe, campos, 'Precalificacion__c');
        agregarCampoSiExiste(contractDescribe, campos, 'Periodo_Pago__c');

        String soql =
            'SELECT ' + String.join(campos, ',') +
            ' FROM Contract WHERE Id IN :contractIds';

        for (SObject contrato : Database.query(soql)) {
            contratosPorId.put((Id) contrato.get('Id'), contrato);
        }

        return contratosPorId;
    }

    /*
     * =====================================================================================
     * VALIDACIÓN DE PRECALIFICACIÓN
     * =====================================================================================
     */
    private static Set<Id> obtenerContratosConPrecalificacionSuficiente(
        Map<Id, SObject> contratosPorId
    ) {

        Set<Id> contratosValidos = new Set<Id>();

        if (contratosPorId == null || contratosPorId.isEmpty()) {
            return contratosValidos;
        }

        Set<Id> precalificacionIds = new Set<Id>();
        Set<Id> contratistaIds = new Set<Id>();

        for (SObject contrato : contratosPorId.values()) {

            Id preId = getId(contrato, 'Precalificacion__c');

            if (preId != null) {
                precalificacionIds.add(preId);
            }

            Id contratistaId = getId(contrato, 'Contratista__c');

            if (contratistaId == null) {
                contratistaId = getId(contrato, 'AccountId');
            }

            if (contratistaId != null) {
                contratistaIds.add(contratistaId);
            }
        }

        if (precalificacionIds.isEmpty() && contratistaIds.isEmpty()) {
            return contratosValidos;
        }

        Set<Id> precalificacionesSuficientes = new Set<Id>();
        Set<Id> contratistasConPrecalificacionSuficiente = new Set<Id>();

        for (Precalificacion__c precalificacion : [
            SELECT Id,
                   ContratistaPrecalificacion__c,
                   Capacidad_Afianzamiento_Calc__c
            FROM Precalificacion__c
            WHERE (
                    Id IN :precalificacionIds
                    OR ContratistaPrecalificacion__c IN :contratistaIds
                  )
              AND Capacidad_Afianzamiento_Calc__c = :CAPACIDAD_SUFICIENTE
        ]) {

            precalificacionesSuficientes.add(precalificacion.Id);

            if (precalificacion.ContratistaPrecalificacion__c != null) {
                contratistasConPrecalificacionSuficiente.add(
                    precalificacion.ContratistaPrecalificacion__c
                );
            }
        }

        for (Id contratoId : contratosPorId.keySet()) {

            SObject contrato = contratosPorId.get(contratoId);

            Id preId = getId(contrato, 'Precalificacion__c');

            Id contratistaId = getId(contrato, 'Contratista__c');

            if (contratistaId == null) {
                contratistaId = getId(contrato, 'AccountId');
            }

            Boolean validoPorPrecalificacion =
                preId != null &&
                precalificacionesSuficientes.contains(preId);

            Boolean validoPorContratista =
                contratistaId != null &&
                contratistasConPrecalificacionSuficiente.contains(contratistaId);

            if (validoPorPrecalificacion || validoPorContratista) {
                contratosValidos.add(contratoId);
            }
        }

        return contratosValidos;
    }

    /*
     * =====================================================================================
     * HELPERS DE SCHEMA
     * =====================================================================================
     */

    /*
     * Versión para Schema.SObjectType.
     */
    private static void agregarCampoSiExiste(
        Schema.SObjectType tipo,
        List<String> campos,
        String campo
    ) {

        if (tipo == null || campos == null || String.isBlank(campo)) {
            return;
        }

        if (
            tipo.getDescribe().fields.getMap().containsKey(campo) &&
            !campos.contains(campo)
        ) {
            campos.add(campo);
        }
    }

    /*
     * Versión para Schema.DescribeSObjectResult.
     * Esta es la corrección del error de compilación.
     */
    private static void agregarCampoSiExiste(
        Schema.DescribeSObjectResult describe,
        List<String> campos,
        String campo
    ) {

        if (describe == null || campos == null || String.isBlank(campo)) {
            return;
        }

        if (
            describe.fields.getMap().containsKey(campo) &&
            !campos.contains(campo)
        ) {
            campos.add(campo);
        }
    }

    private static Boolean campoExiste(
        Schema.SObjectType tipo,
        String campo
    ) {

        if (tipo == null || String.isBlank(campo)) {
            return false;
        }

        return tipo.getDescribe().fields.getMap().containsKey(campo);
    }

    private static Boolean campoExiste(
        Schema.DescribeSObjectResult describe,
        String campo
    ) {

        if (describe == null || String.isBlank(campo)) {
            return false;
        }

        return describe.fields.getMap().containsKey(campo);
    }

    /*
     * =====================================================================================
     * HELPERS DE LECTURA DINÁMICA
     * =====================================================================================
     */
    private static Object getValue(SObject registro, String campo) {

        if (registro == null || String.isBlank(campo)) {
            return null;
        }

        try {
            return registro.get(campo);
        } catch (Exception e) {
            return null;
        }
    }

    private static Id getId(SObject registro, String campo) {

        Object valor = getValue(registro, campo);

        if (valor == null) {
            return null;
        }

        try {
            return (Id) valor;
        } catch (Exception e) {
            return null;
        }
    }

    private static String getString(SObject registro, String campo) {

        Object valor = getValue(registro, campo);

        if (valor == null) {
            return null;
        }

        return String.valueOf(valor);
    }

    private static Date getDate(SObject registro, String campo) {

        Object valor = getValue(registro, campo);

        if (valor == null) {
            return null;
        }

        try {
            return (Date) valor;
        } catch (Exception e) {
            return null;
        }
    }
}