force-app/main/default/objects/Beneficiario__c/Beneficiario__c.object-meta.xml
<CustomObject>
    <label>Beneficiario</label>
    <nameField>
        <label>Nombre de Beneficiario</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beneficiarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Beneficiario__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Beneficiarios</relationshipLabel>
    <relationshipName>Beneficiarios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beneficiario__c/fields/Fianza__c.field-meta.xml
<CustomField>
    <fullName>Fianza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fianza</label>
    <referenceTo>Fianza__c</referenceTo>
    <relationshipLabel>Beneficiarios</relationshipLabel>
    <relationshipName>Beneficiarios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <label>Contrato</label>
    <nameField>
        <label>No. Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato__c/fields/Beneficiario__c.field-meta.xml
<CustomField>
    <fullName>Beneficiario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beneficiario</label>
    <referenceTo>Beneficiario__c</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fianza__c/Fianza__c.object-meta.xml
<CustomObject>
    <label>Fianzassss</label>
    <nameField>
        <label>Número de fianza</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fianzas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fianza__c/fields/Beneficiario__c.field-meta.xml
<CustomField>
    <fullName>Beneficiario__c</fullName>
    <formula>No_Contrato__r.Beneficiario__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Beneficiario</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tech_Relacion__c/Tech_Relacion__c.object-meta.xml
<CustomObject xmlns=\"http://soap.sforce.com/2006/04/metadata\"><deploymentStatus>Deployed</deploymentStatus><label>Relación Técnica</label><nameField><label>ID Relación</label><type>AutoNumber</type></nameField><pluralLabel>Relaciones Técnicas</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

force-app/main/default/objects/Tech_Relacion__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relaciones Técnicas</relationshipLabel>
    <relationshipName>Relaciones_Tecnicas_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Relacion__c/fields/Beneficiario__c.field-meta.xml
<CustomField>
    <fullName>Beneficiario__c</fullName>
    <label>Beneficiario</label>
    <referenceTo>Beneficiario__c</referenceTo>
    <relationshipLabel>Relaciones Técnicas</relationshipLabel>
    <relationshipName>Relaciones_Tecnicas_Beneficiario</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Relacion__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contrato__c</referenceTo>
    <relationshipLabel>Relaciones Técnicas</relationshipLabel>
    <relationshipName>Relaciones_Tecnicas_Contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Relacion__c/fields/Fianza__c.field-meta.xml
<CustomField>
    <fullName>Fianza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fianza</label>
    <referenceTo>Fianza__c</referenceTo>
    <relationshipLabel>Relaciones Técnicas</relationshipLabel>
    <relationshipName>Relaciones_Tecnicas_Fianza</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Relacion__c/fields/Tipo__c.field-meta.xml
<CustomField xmlns=\"http://soap.sforce.com/2006/04/metadata\"><fullName>Tipo__c</fullName><label>Tipo de Relación</label><type>Text</type><length>50</length></CustomField>

force-app/main/default/classes/TechBeneficiarioController.cls
public with sharing class TechBeneficiarioController {
    @AuraEnabled(cacheable=true)
    public static List<TechBeneficiarioWrapper> getBeneficiarioList() {
        List<TechBeneficiarioWrapper> wrappers = new List<TechBeneficiarioWrapper>();
        for (Beneficiario__c b : TechBeneficiarioSelector.getRecentBeneficiarios()) {
            wrappers.add(new TechBeneficiarioWrapper(b));
        }
        return wrappers;
    }

    @AuraEnabled
    public static String saveBeneficiarioWithRelations(Beneficiario__c beneficiario, Map<String, List<String>> relationsMap) {
        try {
            upsert beneficiario;
            List<Tech_Relacion__c> newRelations = new List<Tech_Relacion__c>();
            if (relationsMap != null) {
                for (String type : relationsMap.keySet()) {
                    for (String relatedId : relationsMap.get(type)) {
                        Tech_Relacion__c rel = new Tech_Relacion__c();
                        rel.Account__c = beneficiario.Id; // Usamos Account__c genérico
                        rel.Tipo__c = type;
                        if (type == 'Fianza') rel.Fianza__c = (Id)relatedId;
                        else if (type == 'Contrato') rel.Contrato__c = (Id)relatedId;
                        newRelations.add(rel);
                    }
                }
            }
            if (!newRelations.isEmpty()) insert newRelations;
            return beneficiario.Id;
        } catch (Exception e) {
            throw new AuraHandledException('Error al guardar beneficiario: ' + e.getMessage());
        }
    }
}