force-app/main/default/objects/Afianzadora__c/Afianzadora__c.object-meta.xml
<CustomObject>
    <label>Afianzadora</label>
    <nameField>
        <label>Nombre de Afianzadora</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Afianzadoras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Afianzadora__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Afianzadoras</relationshipLabel>
    <relationshipName>Afianzadoras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Afianzadora__c/fields/Fianza__c.field-meta.xml
<CustomField>
    <fullName>Fianza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fianza</label>
    <referenceTo>Fianza__c</referenceTo>
    <relationshipLabel>Afianzadoras</relationshipLabel>
    <relationshipName>Afianzadoras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Contratista__c.field-meta.xml
<CustomField>
    <fullName>Contratista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratista</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratos (Contratista)</relationshipLabel>
    <relationshipName>Contratos_Contratista</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Vendedores__c</referenceTo>
    <relationshipLabel>Contractos</relationshipLabel>
    <relationshipName>Contractos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contratista__c/Contratista__c.object-meta.xml
<CustomObject>
    <label>Contratista</label>
    <nameField>
        <label>Nombre de Contratista</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratistas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contratista__c/fields/Afianzadora__c.field-meta.xml
<CustomField>
    <fullName>Afianzadora__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Afianzadora</label>
    <referenceTo>Afianzadora__c</referenceTo>
    <relationshipLabel>Contratistas</relationshipLabel>
    <relationshipName>Contratistas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contratista__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contratistas</relationshipLabel>
    <relationshipName>Contratistas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contratista__c/fields/Fianza__c.field-meta.xml
<CustomField>
    <fullName>Fianza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fianza</label>
    <referenceTo>Fianza__c</referenceTo>
    <relationshipLabel>Contratistas</relationshipLabel>
    <relationshipName>Contratistas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <label>Contrato</label>
    <nameField>
        <label>No. Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Endoso__c/Endoso__c.object-meta.xml
<CustomObject>
    <label>Endososss</label>
    <nameField>
        <displayFormat>END - {00000}</displayFormat>
        <label>Número de endoso</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Endosos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Endoso__c/fields/Contratista__c.field-meta.xml
<CustomField>
    <fullName>Contratista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratista</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Endosos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Endoso__c/fields/Fianza__c.field-meta.xml
<CustomField>
    <fullName>Fianza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fianza</label>
    <referenceTo>Fianza__c</referenceTo>
    <relationshipName>Endosos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fianza__c/Fianza__c.object-meta.xml
<CustomObject>
    <label>Fianzassss</label>
    <nameField>
        <label>Número de fianza</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fianzas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fianza__c/fields/Afianzadora__c.field-meta.xml
<CustomField>
    <fullName>Afianzadora__c</fullName>
    <formula>No_Contrato__r.Afianzadora__r.Name</formula>
    <label>Afianzadora</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fianza__c/fields/Contratista__c.field-meta.xml
<CustomField>
    <fullName>Contratista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratista</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Fianzas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fianza__c/fields/Endoso__c.field-meta.xml
<CustomField>
    <fullName>Endoso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Endoso</label>
    <referenceTo>Endoso__c</referenceTo>
    <relationshipName>Fianzas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fianza__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vencida</fullName>
            </value>
            <value>
                <fullName>Vigente</fullName>
            </value>
            <value>
                <fullName>En plazo</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fianza__c/fields/Fecha_de_Emisi_n__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Emisi_n__c</fullName>
    <label>Fecha de Emisión</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fianza__c/fields/Monto_Afianzado__c.field-meta.xml
<CustomField>
    <fullName>Monto_Afianzado__c</fullName>
    <label>Monto Afianzado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fianza__c/fields/No_Contrato__c.field-meta.xml
<CustomField>
    <fullName>No_Contrato__c</fullName>
    <label>No Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipName>Fianzas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fianza__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Vendedores__c</referenceTo>
    <relationshipName>Fianzas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Relacion__c/Tech_Relacion__c.object-meta.xml
<CustomObject xmlns=\"http://soap.sforce.com/2006/04/metadata\"><deploymentStatus>Deployed</deploymentStatus><label>Relación Técnica</label><nameField><label>ID Relación</label><type>AutoNumber</type></nameField><pluralLabel>Relaciones Técnicas</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

force-app/main/default/objects/Tech_Relacion__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relaciones Técnicas</relationshipLabel>
    <relationshipName>Relaciones_Tecnicas_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Relacion__c/fields/Contratista__c.field-meta.xml
<CustomField>
    <fullName>Contratista__c</fullName>
    <label>Contratista</label>
    <referenceTo>Contratista__c</referenceTo>
    <relationshipLabel>Relaciones Técnicas</relationshipLabel>
    <relationshipName>Relaciones_Tecnicas_Contratista</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Relacion__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contrato__c</referenceTo>
    <relationshipLabel>Relaciones Técnicas</relationshipLabel>
    <relationshipName>Relaciones_Tecnicas_Contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Relacion__c/fields/Endoso__c.field-meta.xml
<CustomField>
    <fullName>Endoso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Endoso</label>
    <referenceTo>Endoso__c</referenceTo>
    <relationshipLabel>Relaciones Técnicas</relationshipLabel>
    <relationshipName>Relaciones_Tecnicas_Endoso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Relacion__c/fields/Fianza__c.field-meta.xml
<CustomField>
    <fullName>Fianza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fianza</label>
    <referenceTo>Fianza__c</referenceTo>
    <relationshipLabel>Relaciones Técnicas</relationshipLabel>
    <relationshipName>Relaciones_Tecnicas_Fianza</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Relacion__c/fields/Tipo__c.field-meta.xml
<CustomField xmlns=\"http://soap.sforce.com/2006/04/metadata\"><fullName>Tipo__c</fullName><label>Tipo de Relación</label><type>Text</type><length>50</length></CustomField>

force-app/main/default/objects/Tech_Relacion__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <label>Vendedores</label>
    <referenceTo>Vendedores__c</referenceTo>
    <relationshipLabel>Relaciones Técnicas</relationshipLabel>
    <relationshipName>Relaciones_Tecnicas_Vendedor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendedores__c/Vendedores__c.object-meta.xml
<CustomObject>
    <description>Usuarios que se encargarán de gestionar las ventas</description>
    <label>Vendedorsss</label>
    <nameField>
        <label>Nombre del vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedoresss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TechFianzaSelector.cls
public with sharing class TechFianzaSelector {
    public static List<Fianza__c> getRecentFianzas() {
        return [
            SELECT Id, Name, No_Contrato__c, 
                   Contratista__c, Contratista__r.Name, 
                   Vendedor__c, Vendedor__r.Name, 
                   Estatus__c, Monto_Afianzado__c, Fecha_de_Emisi_n__c, Afianzadora__c,
                   (SELECT Tipo__c, Contrato__r.Name, Account__r.Name, Vendedor__r.Name, Endoso__r.Name 
                    FROM Relaciones_Tecnicas_Fianza__r)
            FROM Fianza__c
            ORDER BY CreatedDate DESC
            LIMIT 50
        ];
    }
}