force-app/main/default/objects/Institucion__c/Institucion__c.object-meta.xml
<CustomObject>
    <label>Institución</label>
    <nameField>
        <label>Nombre de la Institución</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instituciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Institucion__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Instituciones</relationshipLabel>
    <relationshipName>Instituciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Institucion__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activa</fullName>
            </value>
            <value>
                <fullName>Desactiva</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Fecha_Fin_Vigencia__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Fin_Vigencia__c</fullName>
    <label>Fecha Fin Vigencia</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Fecha_Inicio_Vigencia__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Inicio_Vigencia__c</fullName>
    <label>Fecha Inicio Vigencia</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Institucion__c.field-meta.xml
<CustomField>
    <fullName>Institucion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Institución</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Institución</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oportunidades (Institución)</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Metodo_Pago__c.field-meta.xml
<CustomField>
    <fullName>Metodo_Pago__c</fullName>
    <label>Metodo Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Metodo_pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Periodo_Pago__c.field-meta.xml
<CustomField>
    <fullName>Periodo_Pago__c</fullName>
    <label>Periodo Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Periodo_Pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Poliza_Renovar__c.field-meta.xml
<CustomField>
    <fullName>Poliza_Renovar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Poliza Renovar</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Tech_Seguro__c.Estatus__c</field>
            <operation>equals</operation>
            <value>Por renovar</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Tech_Seguro__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ramo__c.field-meta.xml
<CustomField>
    <fullName>Ramo__c</fullName>
    <description>Auto, GMM, Vida, PPR, Daños, Fianzas, Membresía.</description>
    <label>Ramo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Ramos_GVS</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subproducto__c.field-meta.xml
<CustomField>
    <fullName>Subproducto__c</fullName>
    <label>Subproducto</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Vendedor_A__c.field-meta.xml
<CustomField>
    <fullName>Vendedor_A__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Tech_Vendedor__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Vigencia__c.field-meta.xml
<CustomField>
    <fullName>Vigencia__c</fullName>
    <inlineHelpText>Vigencia en Meses</inlineHelpText>
    <label>Vigencia</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tech_Seguro__c/Tech_Seguro__c.object-meta.xml
<CustomObject>
    <label>Seguro</label>
    <nameField>
        <label>Número de póliza</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seguros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tech_Seguro__c/fields/Aseguradora__c.field-meta.xml
<CustomField>
    <fullName>Aseguradora__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aseguradora</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Seguros (Aseguradora)</relationshipLabel>
    <relationshipName>Seguros5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Seguro__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Seguros</relationshipLabel>
    <relationshipName>Seguros3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Seguro__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Emitida</fullName>
                <default>true</default>
                <label>Emitida</label>
            </value>
            <value>
                <fullName>Vigente</fullName>
            </value>
            <value>
                <fullName>Por renovar</fullName>
            </value>
            <value>
                <fullName>Renovada</fullName>
            </value>
            <value>
                <fullName>Vencida</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tech_Seguro__c/fields/Fin_del_seguro__c.field-meta.xml
<CustomField>
    <fullName>Fin_del_seguro__c</fullName>
    <label>Fin del seguro</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tech_Seguro__c/fields/Forma_Pago__c.field-meta.xml
<CustomField>
    <fullName>Forma_Pago__c</fullName>
    <label>Forma de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Metodo_pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tech_Seguro__c/fields/Frecuencia_de_pago__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia_de_pago__c</fullName>
    <label>Frecuencia de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contado</fullName>
            </value>
            <value>
                <fullName>Mensual</fullName>
            </value>
            <value>
                <fullName>Trimestral</fullName>
            </value>
            <value>
                <fullName>Semestral</fullName>
            </value>
            <value>
                <fullName>Anual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tech_Seguro__c/fields/Inicio_del_seguro__c.field-meta.xml
<CustomField>
    <fullName>Inicio_del_seguro__c</fullName>
    <label>Inicio del seguro</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tech_Seguro__c/fields/Prima_neta__c.field-meta.xml
<CustomField>
    <fullName>Prima_neta__c</fullName>
    <label>Prima neta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tech_Seguro__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Seguros</relationshipLabel>
    <relationshipName>Seguros1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Seguro__c/fields/Ramo__c.field-meta.xml
<CustomField>
    <fullName>Ramo__c</fullName>
    <label>Ramo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auto</fullName>
            </value>
            <value>
                <fullName>GMM</fullName>
            </value>
            <value>
                <fullName>Vida</fullName>
            </value>
            <value>
                <fullName>PPR</fullName>
            </value>
            <value>
                <fullName>Daños</fullName>
            </value>
            <value>
                <fullName>RC</fullName>
            </value>
            <value>
                <fullName>Membresía Salud</fullName>
            </value>
            <value>
                <fullName>Fianzas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tech_Seguro__c/fields/Subproducto__c.field-meta.xml
<CustomField>
    <fullName>Subproducto__c</fullName>
    <label>Subproducto</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tech_Seguro__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Tech_Vendedor__c</referenceTo>
    <relationshipLabel>Seguros</relationshipLabel>
    <relationshipName>Seguros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Seguro__c/fields/Vigencia__c.field-meta.xml
<CustomField>
    <fullName>Vigencia__c</fullName>
    <label>Vigencia</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tech_Seguro__c/recordTypes/Auto.recordType-meta.xml
<RecordType>
    <fullName>Auto</fullName>
    <active>true</active>
    <label>Auto</label>
</RecordType>

force-app/main/default/objects/Tech_Seguro__c/recordTypes/Danos.recordType-meta.xml
<RecordType>
    <fullName>Danos</fullName>
    <active>true</active>
    <label>Danos</label>
</RecordType>

force-app/main/default/objects/Tech_Seguro__c/recordTypes/GMM.recordType-meta.xml
<RecordType>
    <fullName>GMM</fullName>
    <active>true</active>
    <label>GMM</label>
</RecordType>

force-app/main/default/objects/Tech_Vendedor__c/Tech_Vendedor__c.object-meta.xml
<CustomObject>
    <label>Vendedor</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>No. Vendedor</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tech Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tech_Vendedor__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>Suspendido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tech_Vendedor__c/fields/Usuario_Salesforce__c.field-meta.xml
<CustomField>
    <fullName>Usuario_Salesforce__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Tech_Vendedores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TechSeguroRenovacionScheduler.cls
public with sharing class TechSeguroRenovacionScheduler implements Schedulable {

    public void execute(SchedulableContext context) {
        procesarRenovaciones();
    }

    public static void procesarRenovaciones() {

        Date hoy = Date.today();
        Date fechaMaxima = hoy.addDays(60);

        List<Tech_Seguro__c> seguros = [
            SELECT Id,
                   Name,
                   Cliente__c,
                   Cliente__r.Name,
                   Vendedor__c,
                   Vendedor__r.Name,
                   Vendedor__r.Email__c,
                   Vendedor__r.Usuario_Salesforce__r.Email,
                   Producto__c,
                   Producto__r.Name,
                   Subproducto__c,
                   Aseguradora__c,
                   Aseguradora__r.Name,
                   Ramo__c,
                   Inicio_del_seguro__c,
                   Fin_del_seguro__c,
                   Prima_neta__c,
                   Forma_Pago__c,
                   Frecuencia_de_pago__c,
                   Vigencia__c,
                   Estatus__c
            FROM Tech_Seguro__c
            WHERE Fin_del_seguro__c != null
              AND Fin_del_seguro__c >= :hoy
              AND Fin_del_seguro__c <= :fechaMaxima
              AND Estatus__c != 'Por renovar'
              AND Estatus__c != 'Renovado'
              AND Estatus__c != 'Cancelado'
        ];

        if (seguros.isEmpty()) {
            return;
        }

        Set<Id> seguroIds = new Set<Id>();

        for (Tech_Seguro__c seguro : seguros) {
            seguroIds.add(seguro.Id);
        }

        Map<Id, Opportunity> oportunidadRenovacionPorSeguro =
            new Map<Id, Opportunity>();

        for (Opportunity opp : [
            SELECT Id,
                   Poliza_Renovar__c,
                   IsClosed
            FROM Opportunity
            WHERE Poliza_Renovar__c IN :seguroIds
              AND IsClosed = false
        ]) {
            oportunidadRenovacionPorSeguro.put(opp.Poliza_Renovar__c, opp);
        }

        List<Tech_Seguro__c> segurosPorActualizar = new List<Tech_Seguro__c>();
        List<Opportunity> oportunidadesPorInsertar = new List<Opportunity>();
        List<Tech_Seguro__c> segurosPorNotificar = new List<Tech_Seguro__c>();

        String etapaInicial = obtenerEtapaInicialOpportunity();

        for (Tech_Seguro__c seguro : seguros) {

            Integer diasAntes = obtenerDiasAntesRenovacion(seguro.Ramo__c);
            Date fechaInicioRenovacion = seguro.Fin_del_seguro__c.addDays(-diasAntes);

            if (hoy < fechaInicioRenovacion) {
                continue;
            }

            seguro.Estatus__c = 'Por renovar';
            segurosPorActualizar.add(seguro);

            if (oportunidadRenovacionPorSeguro.containsKey(seguro.Id)) {
                continue;
            }

            Opportunity oppRenovacion = new Opportunity();

            oppRenovacion.Name = 'Renovación - ' + seguro.Name;
            oppRenovacion.StageName = etapaInicial;
            oppRenovacion.CloseDate = seguro.Fin_del_seguro__c;
            oppRenovacion.AccountId = seguro.Cliente__c;

            oppRenovacion.Vendedor_A__c = seguro.Vendedor__c;
            oppRenovacion.Producto__c = seguro.Producto__c;
            oppRenovacion.Subproducto__c = seguro.Subproducto__c;
            oppRenovacion.Institucion__c = seguro.Aseguradora__c;
            oppRenovacion.Ramo__c = seguro.Ramo__c;

            oppRenovacion.Fecha_Inicio_Vigencia__c =
                seguro.Fin_del_seguro__c.addDays(1);

            if (seguro.Vigencia__c != null && seguro.Vigencia__c > 0) {
                oppRenovacion.Fecha_Fin_Vigencia__c =
                    oppRenovacion.Fecha_Inicio_Vigencia__c.addMonths(
                        seguro.Vigencia__c.intValue()
                    );
            }

            oppRenovacion.Vigencia__c = seguro.Vigencia__c;
            oppRenovacion.Metodo_Pago__c = seguro.Forma_Pago__c;
            oppRenovacion.Periodo_Pago__c = seguro.Frecuencia_de_pago__c;
            oppRenovacion.Amount = seguro.Prima_neta__c;
            oppRenovacion.Poliza_Renovar__c = seguro.Id;

            oportunidadesPorInsertar.add(oppRenovacion);
            segurosPorNotificar.add(seguro);
        }

        if (!segurosPorActualizar.isEmpty()) {
            update segurosPorActualizar;
        }

        if (!oportunidadesPorInsertar.isEmpty()) {
            insert oportunidadesPorInsertar;

            enviarNotificacionesRenovacion(
                segurosPorNotificar,
                oportunidadesPorInsertar
            );
        }
    }

    private static Integer obtenerDiasAntesRenovacion(String ramo) {

        if (String.isBlank(ramo)) {
            return 30;
        }

        if (ramo == 'Auto' || ramo == 'Autos') {
            return 30;
        }

        if (ramo == 'Gastos Médicos' || ramo == 'GMM') {
            return 45;
        }

        if (ramo == 'Vida') {
            return 60;
        }

        if (ramo == 'PPR') {
            return 60;
        }

        if (ramo == 'Daños' || ramo == 'Danos') {
            return 45;
        }

        if (ramo == 'Fianzas' || ramo == 'Fianza') {
            return 30;
        }

        return 30;
    }

    private static String obtenerEtapaInicialOpportunity() {

        List<OpportunityStage> etapas = [
            SELECT MasterLabel
            FROM OpportunityStage
            WHERE IsClosed = false
            ORDER BY SortOrder ASC
            LIMIT 1
        ];

        if (!etapas.isEmpty()) {
            return etapas[0].MasterLabel;
        }

        return 'Prospecting';
    }

    private static void enviarNotificacionesRenovacion(
        List<Tech_Seguro__c> seguros,
        List<Opportunity> oportunidades
    ) {
        if (seguros == null || seguros.isEmpty()) {
            return;
        }

        List<Messaging.SingleEmailMessage> correos =
            new List<Messaging.SingleEmailMessage>();

        for (Integer i = 0; i < seguros.size(); i++) {

            Tech_Seguro__c seguro = seguros[i];
            Opportunity oportunidad = oportunidades[i];

            String emailVendedor;

            if (
                seguro.Vendedor__r != null &&
                !String.isBlank(seguro.Vendedor__r.Email__c)
            ) {
                emailVendedor = seguro.Vendedor__r.Email__c;
            } else if (
                seguro.Vendedor__r != null &&
                seguro.Vendedor__r.Usuario_Salesforce__r != null &&
                !String.isBlank(seguro.Vendedor__r.Usuario_Salesforce__r.Email)
            ) {
                emailVendedor = seguro.Vendedor__r.Usuario_Salesforce__r.Email;
            }

            if (String.isBlank(emailVendedor)) {
                continue;
            }

            String nombreVendedor = seguro.Vendedor__r != null
                ? seguro.Vendedor__r.Name
                : 'Vendedor';

            String nombreCliente = seguro.Cliente__r != null
                ? seguro.Cliente__r.Name
                : 'Cliente no especificado';

            String nombreProducto = seguro.Producto__r != null
                ? seguro.Producto__r.Name
                : 'Producto no especificado';

            String nombreAseguradora = seguro.Aseguradora__r != null
                ? seguro.Aseguradora__r.Name
                : 'Aseguradora no especificada';

            String asunto = 'Renovación próxima - ' + seguro.Name;

            String cuerpo =
                'Hola ' + nombreVendedor + ',\n\n' +
                'Se ha generado una oportunidad de renovación para el siguiente seguro:\n\n' +
                'Cliente: ' + nombreCliente + '\n' +
                'Seguro: ' + seguro.Name + '\n' +
                'Ramo: ' + seguro.Ramo__c + '\n' +
                'Producto: ' + nombreProducto + '\n' +
                'Aseguradora: ' + nombreAseguradora + '\n' +
                'Fecha de vencimiento: ' + String.valueOf(seguro.Fin_del_seguro__c) + '\n' +
                'Prima actual: $' + String.valueOf(seguro.Prima_neta__c) + '\n\n' +
                'Oportunidad creada: ' + oportunidad.Name + '\n' +
                'Fecha estimada de cierre: ' + String.valueOf(oportunidad.CloseDate) + '\n\n' +
                'Acción requerida:\n' +
                '1. Contactar al cliente.\n' +
                '2. Confirmar condiciones de renovación.\n' +
                '3. Actualizar la oportunidad con la nueva propuesta.\n\n' +
                'Este mensaje fue generado automáticamente por Salesforce.\n';

            Messaging.SingleEmailMessage correo =
                new Messaging.SingleEmailMessage();

            correo.setToAddresses(new List<String>{ emailVendedor });
//            correo.setReplyTo('abner.trujillo@technovalue.com.mx');
            correo.setSenderDisplayName('Ollin Protección');
            correo.setSubject(asunto);
            correo.setPlainTextBody(cuerpo);
            correo.setSaveAsActivity(false);

            correos.add(correo);
        }

        if (!correos.isEmpty()) {
            try {
                Messaging.sendEmail(correos, false);
            } catch (Exception e) {
                System.debug(
                    'Error al enviar notificaciones de renovación: ' +
                    e.getMessage()
                );
            }
        }
    }

    public static void programarDiario() {

        String cron = '0 0 2 * * ?';

        System.schedule(
            'TECH - Renovación diaria de seguros',
            cron,
            new TechSeguroRenovacionScheduler()
        );
    }
}