force-app/main/default/objects/Contratista__c/Contratista__c.object-meta.xml
<CustomObject>
    <label>Contratista</label>
    <nameField>
        <label>Nombre de Contratista</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratistas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contratista__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contratistas</relationshipLabel>
    <relationshipName>Contratistas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contratista__c/fields/Fianza__c.field-meta.xml
<CustomField>
    <fullName>Fianza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fianza</label>
    <referenceTo>Fianza__c</referenceTo>
    <relationshipLabel>Contratistas</relationshipLabel>
    <relationshipName>Contratistas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <label>Contrato</label>
    <nameField>
        <label>No. Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato__c/fields/Contratista__c.field-meta.xml
<CustomField>
    <fullName>Contratista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratista</label>
    <referenceTo>Contratista__c</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos_Contratista</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <formula>IF(
    TODAY() &lt;=  Fin_de_Contrato__c ,
    &quot;En plazo&quot;,
    &quot;Vencido&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estatus</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fianza__c/Fianza__c.object-meta.xml
<CustomObject>
    <label>Fianzassss</label>
    <nameField>
        <label>Número de fianza</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fianzas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fianza__c/fields/Contratista__c.field-meta.xml
<CustomField>
    <fullName>Contratista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratista</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Fianzas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fianza__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vencida</fullName>
            </value>
            <value>
                <fullName>Vigente</fullName>
            </value>
            <value>
                <fullName>En plazo</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fianza__c/fields/Fecha_de_Emisi_n__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Emisi_n__c</fullName>
    <label>Fecha de Emisión</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fianza__c/fields/Monto_Afianzado__c.field-meta.xml
<CustomField>
    <fullName>Monto_Afianzado__c</fullName>
    <label>Monto Afianzado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fianza__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Vendedores__c</referenceTo>
    <relationshipName>Fianzas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Relacion__c/Tech_Relacion__c.object-meta.xml
<CustomObject xmlns=\"http://soap.sforce.com/2006/04/metadata\"><deploymentStatus>Deployed</deploymentStatus><label>Relación Técnica</label><nameField><label>ID Relación</label><type>AutoNumber</type></nameField><pluralLabel>Relaciones Técnicas</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

force-app/main/default/objects/Tech_Relacion__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relaciones Técnicas</relationshipLabel>
    <relationshipName>Relaciones_Tecnicas_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Relacion__c/fields/Contratista__c.field-meta.xml
<CustomField>
    <fullName>Contratista__c</fullName>
    <label>Contratista</label>
    <referenceTo>Contratista__c</referenceTo>
    <relationshipLabel>Relaciones Técnicas</relationshipLabel>
    <relationshipName>Relaciones_Tecnicas_Contratista</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Relacion__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contrato__c</referenceTo>
    <relationshipLabel>Relaciones Técnicas</relationshipLabel>
    <relationshipName>Relaciones_Tecnicas_Contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Relacion__c/fields/Fianza__c.field-meta.xml
<CustomField>
    <fullName>Fianza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fianza</label>
    <referenceTo>Fianza__c</referenceTo>
    <relationshipLabel>Relaciones Técnicas</relationshipLabel>
    <relationshipName>Relaciones_Tecnicas_Fianza</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Relacion__c/fields/Tipo__c.field-meta.xml
<CustomField xmlns=\"http://soap.sforce.com/2006/04/metadata\"><fullName>Tipo__c</fullName><label>Tipo de Relación</label><type>Text</type><length>50</length></CustomField>

force-app/main/default/objects/Tech_Relacion__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <label>Vendedores</label>
    <referenceTo>Vendedores__c</referenceTo>
    <relationshipLabel>Relaciones Técnicas</relationshipLabel>
    <relationshipName>Relaciones_Tecnicas_Vendedor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendedores__c/Vendedores__c.object-meta.xml
<CustomObject>
    <description>Usuarios que se encargarán de gestionar las ventas</description>
    <label>Vendedorsss</label>
    <nameField>
        <label>Nombre del vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedoresss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TechFianzaWrapper.cls
public class TechFianzaWrapper {
    @AuraEnabled public String id { get; set; }
    @AuraEnabled public String name { get; set; }
    @AuraEnabled public List<String> contratistas { get; set; }
    @AuraEnabled public List<String> vendedores { get; set; }
    @AuraEnabled public List<String> contratos { get; set; }
    @AuraEnabled public String estatus { get; set; }
    @AuraEnabled public String estatusClass { get; set; }
    @AuraEnabled public Decimal monto { get; set; }
    @AuraEnabled public Date fechaEmision { get; set; }

    public TechFianzaWrapper(Fianza__c f) {
        this.id = f.Id;
        this.name = f.Name;
        this.estatus = f.Estatus__c;
        this.monto = f.Monto_Afianzado__c;
        this.fechaEmision = f.Fecha_de_Emisi_n__c;
        
        this.contratistas = new List<String>();
        this.vendedores = new List<String>();
        this.contratos = new List<String>();

        // 1. Agregar el registro principal primero si existe
        if (f.Contratista__r != null) this.contratistas.add(f.Contratista__r.Name);
        if (f.Vendedor__r != null) this.vendedores.add(f.Vendedor__r.Name);

        // 2. Procesar las relaciones múltiples adicionales (evitando duplicar el principal)
        for (Tech_Relacion__c rel : f.Relaciones_Tecnicas_Fianza__r) {
            if (rel.Tipo__c == 'Contratista' && rel.Account__r.Name != null) {
                if (!this.contratistas.contains(rel.Account__r.Name)) {
                    this.contratistas.add(rel.Account__r.Name);
                }
            } else if (rel.Tipo__c == 'Vendedor' && rel.Vendedor__r.Name != null) {
                if (!this.vendedores.contains(rel.Vendedor__r.Name)) {
                    this.vendedores.add(rel.Vendedor__r.Name);
                }
            } else if (rel.Tipo__c == 'Contrato' && rel.Contrato__r.Name != null) {
                if (!this.contratos.contains(rel.Contrato__r.Name)) {
                    this.contratos.add(rel.Contrato__r.Name);
                }
            }
        }

        if (f.Estatus__c == 'Activa') this.estatusClass = 'airtable-badge-green';
        else if (f.Estatus__c == 'Pendiente') this.estatusClass = 'airtable-badge-orange';
        else this.estatusClass = 'airtable-badge-gray';
    }
}