force-app/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <label>Contrato</label>
    <nameField>
        <label>No. Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato__c/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proyecto__c/Proyecto__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre de Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proyecto__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contrato__c</referenceTo>
    <relationshipLabel>Proyectos</relationshipLabel>
    <relationshipName>Proyectos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Relacion__c/Tech_Relacion__c.object-meta.xml
<CustomObject xmlns=\"http://soap.sforce.com/2006/04/metadata\"><deploymentStatus>Deployed</deploymentStatus><label>Relación Técnica</label><nameField><label>ID Relación</label><type>AutoNumber</type></nameField><pluralLabel>Relaciones Técnicas</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

force-app/main/default/objects/Tech_Relacion__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relaciones Técnicas</relationshipLabel>
    <relationshipName>Relaciones_Tecnicas_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Relacion__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contrato__c</referenceTo>
    <relationshipLabel>Relaciones Técnicas</relationshipLabel>
    <relationshipName>Relaciones_Tecnicas_Contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Relacion__c/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Relaciones Técnicas</relationshipLabel>
    <relationshipName>Relaciones_Tecnicas_Proyecto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tech_Relacion__c/fields/Tipo__c.field-meta.xml
<CustomField xmlns=\"http://soap.sforce.com/2006/04/metadata\"><fullName>Tipo__c</fullName><label>Tipo de Relación</label><type>Text</type><length>50</length></CustomField>

force-app/main/default/classes/TechProyectoController.cls
public with sharing class TechProyectoController {
    @AuraEnabled(cacheable=true)
    public static List<TechProyectoWrapper> getProyectosList() {
        List<TechProyectoWrapper> wrappers = new List<TechProyectoWrapper>();
        for (Proyecto__c p : TechProyectoSelector.getRecentProyectos()) {
            wrappers.add(new TechProyectoWrapper(p));
        }
        return wrappers;
    }

    @AuraEnabled
    public static String saveProyectoWithRelations(Proyecto__c proyecto, Map<String, List<String>> relationsMap) {
        try {
            upsert proyecto;
            List<Tech_Relacion__c> newRelations = new List<Tech_Relacion__c>();
            if (relationsMap != null) {
                for (String type : relationsMap.keySet()) {
                    for (String relatedId : relationsMap.get(type)) {
                        Tech_Relacion__c rel = new Tech_Relacion__c();
                        rel.Proyecto__c = proyecto.Id;
                        rel.Tipo__c = type;
                        if (type == 'Beneficiario') rel.Account__c = (Id)relatedId;
                        else if (type == 'Contrato') rel.Contrato__c = (Id)relatedId;
                        newRelations.add(rel);
                    }
                }
            }
            if (!newRelations.isEmpty()) insert newRelations;
            return proyecto.Id;
        } catch (Exception e) {
            throw new AuraHandledException('Error al guardar proyecto: ' + e.getMessage());
        }
    }
}